### ISSUE TITLE
Commit Comments

### ISSUE THREAD

**Issue by KatelynBoettcher** [cmelab/QD-Paper-RDF#10]
I noticed that a lot of the commits have identical comments. Is this consistancy helpful for the group? Or would we prefer more unique comments to be made to clearly show what is happening?

**Comment by gwenwhite** [comment]
I am in favor of the idea of unique comments! In addition, maybe we could also aim for short and sweet comments too? This combo could allow for a detailed understanding of the commit, while also not intensifying the ease of a commit message.

**Comment by erjank** [comment]
Katelyn and Gwen said so.
