### ISSUE TITLE
None of the functions have any documentation

### ISSUE THREAD

**Issue by erjank** [cmelab/QD-Paper-RDF#6]
To understand how any of the functions work, I have to read all the code.
It would be much nicer to have documentation like on the internet to understand how everything works, and what's required when calling a function, and what that function returns. 

Need documentation for get_dots2 and plot_rdf.

**Comment by KatelynBoettcher** [comment]
To Do:
1. mention the return
2. complete defining what micron is

**Comment by erjank** [comment]
Katelyn, Rainier, and Christian added documentation last week.
